# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FacetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_found', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.Facet')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.ManyToManyField(to='index_monitor_app.Filter')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='index_monitor_app.Host')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.ResponseData'),
        ),
        migrations.AddField(
            model_name='response',
            name='index_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_node', to='index_monitor_app.Host'),
        ),
        migrations.AddField(
            model_name='facetcount',
            name='facet_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.FacetValue'),
        ),
        migrations.AddField(
            model_name='facetcount',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.Response'),
        ),
    ]
