# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_monitor_app', '0002_auto_20200609_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetcount',
            name='response',
        ),
        migrations.AddField(
            model_name='facetcount',
            name='response_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.ResponseData'),
            preserve_default=False,
        ),
    ]
