# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_monitor_app', '0003_auto_20200609_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('facets', models.ManyToManyField(to='index_monitor_app.Facet')),
                ('filters', models.ManyToManyField(to='index_monitor_app.Filter')),
            ],
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filters',
        ),
        migrations.DeleteModel(
            name='Filters',
        ),
    ]
