# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_monitor_app', '0004_auto_20200609_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='query_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.QueryType'),
            preserve_default=False,
        ),
    ]
