# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_monitor_app', '0005_response_query_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetValueCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('facet_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.FacetValue')),
                ('response_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_monitor_app.ResponseData')),
            ],
        ),
        migrations.RemoveField(
            model_name='facetcount',
            name='facet_value',
        ),
        migrations.RemoveField(
            model_name='facetcount',
            name='response_data',
        ),
        migrations.DeleteModel(
            name='FacetCount',
        ),
    ]
