# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_monitor_app', '0006_auto_20200609_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facet',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='querytype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
